### ISSUE TITLE
No minions matched the target. No command was sent, no jid was assigned.

### ISSUE THREAD

**Issue by arthurzenika** [webedia-dev/pepperboard#5]
I'm trying to get pepperboard to run as a normal user with a root salt-master (next step is to get it to work with a userland salt-master, but that's another topic). 

With the publisher_acl and the ``` chmod 755 /var/cache/salt /var/cache/salt/master /var/cache/salt/master/jobs /var/run/salt /var/run/salt/master ``` I can get the following salt command : 

```
user@host $ salt \* pkg.list_upgrades
[WARNING ] jid does not exist
[WARNING ] Returner unavailable: 
host:
    ----------
    deja-dup:
        34.2-0ubuntu3.1
    deja-dup-backend-gvfs:
        34.2-0ubuntu3.1
    [snip]
```
but the with pepperboard I get : 
```
arthur@ursa:~/local/pepperboard$ pepperboard -d 'upgrades' -o 'upgrades.html' -t 1
No minions matched the target. No command was sent, no jid was assigned.
[snip] 
No minions matched the target. No command was sent, no jid was assigned.
```

(a lot of lines go past)

and upgrades.html gets a unreachable minions exception #3 (longer than the no salt-master exception)

**Comment by arthurzenika** [comment]
There seems to be a permission missing in the README example, going full open bar gets the job done : 

```
publisher_acl:
  arthur:
    - .*
```

**Comment by davromaniak** [comment]
Hi.

First, I would need to correct the README file, in order to have the correct documentation.

In #3, I will do the needed modification in the code part.

Thanks.
